### ISSUE TITLE
No option to create a fingerprint, if not already saved on device

### ISSUE THREAD

**Issue by usamaabrar22** [omaflak/Android-Fingerprint-Example#1]
Hello,
You have done with pretty straight-forward code which is interesting.
I am looking to find a method where I can take fingerprint input, save it somewhere and then compare it with new input.

I don't want to use already saved fingerprints in device.

Thanks.

**Comment by omaraflak** [comment]
Hi @usamaabrar22,
Unfortunately you can't. The fingerprint information is stored within the internal memory of the fingerprint scanner, you don't have access to it. You can only check if a fingerprint was already entered previously.
